#!/usr/bin/env python3
"""Write the typed receipt for an oracle harness run (hamma#122).

Binds: producer commit, oracle identity (image + digest), artifact SHA-256s,
and the success/mismatch case outcomes. The phase-a contract's completion
authority validates against this receipt shape."""
import hashlib
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    out_dir = Path(sys.argv[1])
    image = sys.argv[2]

    success = out_dir / "success-transcript.json"
    mismatch = out_dir / "mismatch-transcript.json"
    for artifact in (success, mismatch):
        if not artifact.exists():
            print(f"missing artifact: {artifact}", file=sys.stderr)
            return 1

    success_doc = json.loads(success.read_text())
    mismatch_doc = json.loads(mismatch.read_text())
    if not success_doc.get("handshake_completed"):
        print("success case did not complete the handshake", file=sys.stderr)
        return 1
    if mismatch_doc.get("handshake_completed"):
        print("mismatch case completed the handshake (must be refused)", file=sys.stderr)
        return 1

    engine = os.environ.get("HAMMA_ORACLE_ENGINE") or (
        "podman" if shutil.which("podman") else "docker"
    )
    # WHY the fallback chain: podman exposes .Digest; docker's local inspect
    # answers RepoDigests for pulled images and .Id always. All three are
    # content-addressed identities of the oracle image.
    digest = ""
    for fmt in ("{{.Digest}}", "{{index .RepoDigests 0}}", "{{.Id}}"):
        probe = subprocess.run(
            [engine, "image", "inspect", image, "--format", fmt],
            capture_output=True, text=True,
        )
        if probe.returncode == 0 and probe.stdout.strip():
            digest = probe.stdout.strip()
            break
    if not digest:
        print(f"could not resolve image digest for {image} via {engine}", file=sys.stderr)
        return 1
    commit = subprocess.run(
        ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True,
    ).stdout.strip()

    receipt = f'''# TS2021 capability-version handshake oracle receipt (hamma#122)
# Generated by tools/oracle/write_receipt.py — do not hand-edit.
schema = 1
created_at = "{datetime.now(timezone.utc).isoformat()}"
producer_commit = "{commit}"

[oracle]
identity = "{image}"
digest = "{digest}"
independence = "headscale is an independent Go implementation of the Tailscale control plane; it shares no code with dictyon"

[artifacts]
success_transcript = {{ path = "{success.name}", sha256 = "{sha256(success)}" }}
mismatch_transcript = {{ path = "{mismatch.name}", sha256 = "{sha256(mismatch)}" }}

[outcome]
success_case_completed = true
mismatch_case_refused = true
capability_version = {success_doc["capability_version"]}
prologue = "{success_doc["prologue"]}"
'''
    receipt_path = out_dir / "receipt.toml"
    receipt_path.write_text(receipt)
    print(f"wrote {receipt_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
